/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DatVeMayBay;

import Controller.Main;
import java.awt.CardLayout;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Admin
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    CardLayout cardLayout;
    public Admin() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        cardLayout = (CardLayout)(jPanel2.getLayout());
        KHlist();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnShowKH = new javax.swing.JButton();
        btnShowCB = new javax.swing.JButton();
        btnShowTK = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhachHang = new javax.swing.JTable();
        btnAddKH = new javax.swing.JButton();
        btnFixKH = new javax.swing.JButton();
        btnDelKH = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfMaKH = new javax.swing.JTextField();
        tfHoTen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfNgaySinh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfSDT = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfMatKhau = new javax.swing.JTextField();
        Nam = new javax.swing.JRadioButton();
        Nu = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        tfFindidKH = new javax.swing.JTextField();
        btnFindidKH = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        tfCMT = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblKhachHang1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblChuyenBay = new javax.swing.JTable();
        btnAddCB = new javax.swing.JButton();
        btnDelCB = new javax.swing.JButton();
        btnFixCB = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tfMaCB = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfDDi = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfDDen = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfTgDi = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfTgDen = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfKC = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tfCP = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tfFindidCB = new javax.swing.JTextField();
        btnFindidCB = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        tfSG = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblChuyenBay1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblThongKe = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lbMaKH = new javax.swing.JLabel();
        lbHoTen = new javax.swing.JLabel();
        lbMaCB = new javax.swing.JLabel();
        lbDDi = new javax.swing.JLabel();
        lbDDen = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        lbVeNgL = new javax.swing.JLabel();
        lbVeTrE = new javax.swing.JLabel();
        lbVeSoS = new javax.swing.JLabel();
        lbTCP = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        lbHL = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        lbHG = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        lbVKH = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        btnShowKH.setForeground(new java.awt.Color(255, 255, 255));
        btnShowKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/output-onlinepngtools (14).png"))); // NOI18N
        btnShowKH.setText("Khách hàng");
        btnShowKH.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnShowKH.setBorderPainted(false);
        btnShowKH.setContentAreaFilled(false);
        btnShowKH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnShowKH.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnShowKH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnShowKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowKHActionPerformed(evt);
            }
        });

        btnShowCB.setForeground(new java.awt.Color(255, 255, 255));
        btnShowCB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/output-onlinepngtools (10).png"))); // NOI18N
        btnShowCB.setText("Chuyến bay");
        btnShowCB.setBorderPainted(false);
        btnShowCB.setContentAreaFilled(false);
        btnShowCB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnShowCB.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnShowCB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnShowCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowCBActionPerformed(evt);
            }
        });

        btnShowTK.setForeground(new java.awt.Color(255, 255, 255));
        btnShowTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/output-onlinepngtools (17).png"))); // NOI18N
        btnShowTK.setText("Thống kê");
        btnShowTK.setBorderPainted(false);
        btnShowTK.setContentAreaFilled(false);
        btnShowTK.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnShowTK.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnShowTK.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnShowTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowTKActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/output-onlinepngtools (30).png"))); // NOI18N
        jButton1.setText("Đăng xuất");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnShowKH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnShowTK, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnShowCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnShowKH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnShowCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnShowTK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );

        jPanel2.setLayout(new java.awt.CardLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhachHang);
        if (tblKhachHang.getColumnModel().getColumnCount() > 0) {
            tblKhachHang.getColumnModel().getColumn(0).setResizable(false);
            tblKhachHang.getColumnModel().getColumn(1).setResizable(false);
            tblKhachHang.getColumnModel().getColumn(2).setResizable(false);
            tblKhachHang.getColumnModel().getColumn(3).setResizable(false);
        }

        btnAddKH.setText("Thêm khách hàng");
        btnAddKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddKHActionPerformed(evt);
            }
        });

        btnFixKH.setText("Sửa thông tin");
        btnFixKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFixKHActionPerformed(evt);
            }
        });

        btnDelKH.setText("Xóa khách hàng");
        btnDelKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelKHActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã khách hàng");

        tfMaKH.setEditable(false);

        jLabel3.setText("Họ và tên");

        jLabel4.setText("Giới tính");

        jLabel5.setText("Ngày sinh");

        jLabel6.setText("Số điện thoại");

        jLabel7.setText("Email");

        jLabel8.setText("Mật khẩu");

        buttonGroup1.add(Nam);
        Nam.setText("Nam");
        Nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamActionPerformed(evt);
            }
        });

        buttonGroup1.add(Nu);
        Nu.setText("Nữ");

        jLabel16.setText("Tìm kiếm mã khách hàng");

        btnFindidKH.setText("Tìm kiếm");
        btnFindidKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindidKHActionPerformed(evt);
            }
        });

        jLabel24.setText("Chứng minh thư");

        tfCMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCMTActionPerformed(evt);
            }
        });

        tblKhachHang1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhachHang1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHang1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblKhachHang1);
        if (tblKhachHang1.getColumnModel().getColumnCount() > 0) {
            tblKhachHang1.getColumnModel().getColumn(0).setResizable(false);
            tblKhachHang1.getColumnModel().getColumn(1).setResizable(false);
            tblKhachHang1.getColumnModel().getColumn(2).setResizable(false);
            tblKhachHang1.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(tfFindidKH, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFindidKH)
                        .addGap(40, 40, 40)
                        .addComponent(btnAddKH))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 7, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(tfSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(tfHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(tfNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(tfMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)
                            .addComponent(tfCMT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFixKH)
                            .addComponent(btnDelKH))
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Nam)
                        .addGap(95, 95, 95)
                        .addComponent(Nu)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfCMT, tfEmail, tfHoTen, tfMaKH, tfMatKhau, tfNgaySinh, tfSDT});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tfMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(tfHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nam)
                            .addComponent(Nu))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(tfNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel6))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(tfSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(tfFindidKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFindidKH)
                            .addComponent(btnAddKH))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel24)
                        .addGap(23, 23, 23)
                        .addComponent(tfCMT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(tfMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFixKH)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelKH)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.add(jPanel3, "jPanel3");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        tblChuyenBay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblChuyenBay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChuyenBayMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblChuyenBay);

        btnAddCB.setText("Thêm chuyến bay");
        btnAddCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCBActionPerformed(evt);
            }
        });

        btnDelCB.setText("Xóa chuyến bay");
        btnDelCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelCBActionPerformed(evt);
            }
        });

        btnFixCB.setText("Sửa thông tin");
        btnFixCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFixCBActionPerformed(evt);
            }
        });

        jLabel9.setText("Mã chuyến bay");

        tfMaCB.setEditable(false);

        jLabel10.setText("Địa điểm đi");

        jLabel11.setText("Địa điểm đến");

        jLabel12.setText("Thời gian khởi hành");

        jLabel13.setText("Thời gian đến nơi");

        jLabel14.setText("Khoảng cách");

        jLabel15.setText("Chi phí");

        jLabel17.setText("Tìm kiếm mã chuyến bay");

        btnFindidCB.setText("Tìm kiếm");
        btnFindidCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindidCBActionPerformed(evt);
            }
        });

        jLabel23.setText("Số ghế");

        tblChuyenBay1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblChuyenBay1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChuyenBay1MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblChuyenBay1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(tfFindidCB, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFindidCB)
                        .addGap(216, 216, 216)
                        .addComponent(btnAddCB))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(tfCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfKC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(tfDDi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(tfDDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(tfTgDi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(tfTgDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMaCB, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(btnFixCB)
                    .addComponent(btnDelCB))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfCP, tfDDen, tfDDi, tfKC, tfMaCB, tfSG, tfTgDen, tfTgDi});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(tfMaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(tfDDi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(tfDDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(tfTgDi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)))
                .addGap(18, 18, 18)
                .addComponent(tfTgDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(tfFindidCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFindidCB)
                            .addComponent(btnAddCB))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(tfKC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfSG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(tfCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFixCB)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelCB)
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfKC, tfSG});

        jPanel2.add(jPanel4, "jPanel4");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        tblThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThongKeMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblThongKe);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel18.setText("Mã khách hàng:");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel19.setText("Họ và tên:");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel20.setText("Mã chuyến bay:");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel21.setText("Địa điểm đi:");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel22.setText("Địa điểm đến:");

        lbMaKH.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lbHoTen.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lbMaCB.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lbDDi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lbDDen.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel28.setText("Vé người lớn:");

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel29.setText("Vé trẻ em:");

        jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel30.setText("Vé sơ sinh:");

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel31.setText("Tổng chi phí:");

        lbVeNgL.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lbVeTrE.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lbVeSoS.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lbTCP.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel32.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel32.setText("Hành lý:");

        lbHL.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel33.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel33.setText("Hạng ghế:");

        lbHG.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel34.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel34.setText("Vé khứ hồi:");

        lbVKH.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel29))
                    .addComponent(jLabel30))
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbVeSoS)
                    .addComponent(lbVeNgL)
                    .addComponent(lbDDen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbDDi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbMaCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbVeTrE))
                .addGap(372, 372, 372)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel34)
                            .addComponent(jLabel33))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbHG, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbHL, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbVKH, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(lbTCP, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lbDDen, lbDDi, lbMaCB, lbMaKH, lbVeNgL, lbVeSoS, lbVeTrE});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel18)
                                            .addComponent(lbMaKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jLabel20)
                                    .addComponent(lbMaCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel21))))
                            .addComponent(lbDDi, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbHL, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel32)
                                .addComponent(jLabel22))))
                    .addComponent(lbDDen))
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbHG, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbVeNgL))
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbVKH, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29)))
                    .addComponent(lbVeTrE, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel31)
                        .addComponent(jLabel30))
                    .addComponent(lbTCP)
                    .addComponent(lbVeSoS))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lbDDen, lbDDi, lbMaCB, lbMaKH, lbTCP, lbVeNgL, lbVeSoS});

        jPanel2.add(jPanel5, "jPanel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowKHActionPerformed
        // TODO add your handling code here:
        cardLayout.show(jPanel2,"jPanel3");
        KHlist();
    }//GEN-LAST:event_btnShowKHActionPerformed

    private void btnShowCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowCBActionPerformed
        // TODO add your handling code here:
        cardLayout.show(jPanel2,"jPanel4");
        CBlist();
    }//GEN-LAST:event_btnShowCBActionPerformed

    private void btnShowTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowTKActionPerformed
        // TODO add your handling code here:
        cardLayout.show(jPanel2,"jPanel5");
        GDlist();
    }//GEN-LAST:event_btnShowTKActionPerformed

    private void btnDelCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelCBActionPerformed
        // TODO add your handling code here:
        int i = tblChuyenBay.getSelectedRow();
        String delMaCB = tblChuyenBay.getValueAt(i,1).toString();
        String tvSQL = "delete from ChuyenBay where MaCB = " +delMaCB;
        Main.connection.cnSQL("jdbc:sqlserver://DESKTOP-JJSJBVA\\SQLEXPRESS:1433;databaseName=QLDV;", "nhom13","9876543210");
        System.out.println(tvSQL);
        try{
            Main.connection.ChinhSuaThongTin(tvSQL);
            JOptionPane.showMessageDialog(null,"Xóa thành công");
        }
        catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Xóa thất bại");
                }
    }//GEN-LAST:event_btnDelCBActionPerformed

    private void btnFixCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFixCBActionPerformed
        // TODO add your handling code here:
        int i = tblChuyenBay.getSelectedRow();
        String FixMaCB = tblChuyenBay.getValueAt(i,1).toString();
        if (KiemTraRongCB()== true){
            JOptionPane.showMessageDialog(null,"Bạn chưa nhập đủ thông tin");
        }
        else{
            try{
                ChuyenBay cb = new ChuyenBay (tfDDi.getText(), tfDDen.getText(), tfTgDi.getText(), tfTgDen.getText(), tfKC.getText(),Integer.parseInt(tfSG.getText()),Integer.parseInt(tfCP.getText()));
                String tvSQL = "update ChuyenBay set DiemDi = N'" + cb.DiemDi + " ', DiemDen = N'" + cb.DiemDen + "', TgDi = N'" + cb.TgDi + "', TgDen = N'" + cb.TgDen + "', KhoangCach = N'" + cb.KhoangCach +"', ChiPhi = N'" +cb.ChiPhi +"' where MaCB =" +FixMaCB;
                Main.connection.cnSQL("jdbc:sqlserver://DESKTOP-JJSJBVA\\SQLEXPRESS:1433;databaseName=QLDV;", "nhom13","9876543210");
                System.out.println(tvSQL);
                Main.connection.ChinhSuaThongTin(tvSQL);
                JOptionPane.showMessageDialog(null,"Sửa thành công");
            }
            catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Sửa thất bại");
                }
        }
    
    }//GEN-LAST:event_btnFixCBActionPerformed

    private void btnAddCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCBActionPerformed
        // TODO add your handling code here:
        ThemCB AddCB = new ThemCB();
        AddCB.show();
        this.dispose();
    }//GEN-LAST:event_btnAddCBActionPerformed

    private void btnAddKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddKHActionPerformed
        // TODO add your handling code here:
        ThemKH tkh = new ThemKH();
        tkh.show();
        this.dispose();
    }//GEN-LAST:event_btnAddKHActionPerformed

    private void btnFixKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFixKHActionPerformed
        // TODO add your handling code here:
        int i = tblKhachHang.getSelectedRow();
        String FixMaKH = tblKhachHang.getValueAt(i,1).toString();
        if (KiemTraRongKH()== true){
            JOptionPane.showMessageDialog(null,"Bạn chưa nhập đủ thông tin");
        }
        else{
            try{
                KhachHang kh = new KhachHang (tfHoTen.getText(),Nam.isSelected() ? "Nam" : "Nu",tfNgaySinh.getText(), tfSDT.getText(), tfEmail.getText(),tfCMT.getText(),tfMatKhau.getText());
                String tvSQL = "update KhachHang set HoTen = N'" + kh.HoTen + " ', GioiTinh = N'" + kh.GioiTinh + "', NgaySinh = N'" + kh.NgaySinh + "', SDT = N'" + kh.SDT + "', Email = N'" + kh.Email +"', MatKhau = N'" +kh.MatKhau +"' where MaKH =" +FixMaKH;
                Main.connection.cnSQL("jdbc:sqlserver://DESKTOP-JJSJBVA\\SQLEXPRESS:1433;databaseName=QLDV;", "nhom13","9876543210");
                System.out.println(tvSQL);
                Main.connection.ChinhSuaThongTin(tvSQL);
                JOptionPane.showMessageDialog(null,"Sửa thành công");
            }
            catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Sửa thất bại");
                }
        }
        cardLayout.show(jPanel2,"jPanel5");
    }//GEN-LAST:event_btnFixKHActionPerformed

    private void NamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamActionPerformed

    private void tblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMouseClicked
        // TODO add your handling code here:
        int i = tblKhachHang.getSelectedRow();
        TableModel model1=tblKhachHang.getModel();
        tfMaKH.setText(model1.getValueAt(i,1).toString());
        String MaKHsl = model1.getValueAt(i,1).toString();
        tfHoTen.setText(model1.getValueAt(i,2).toString());
        String gioitinh = model1.getValueAt(i,3).toString();
            if(gioitinh.equals("Nam")){
                Nam.setSelected(true);
            }
            else{
                Nu.setSelected(true);
            }
        tfNgaySinh.setText(model1.getValueAt(i,4).toString());
        tfSDT.setText(model1.getValueAt(i,5).toString());
        tfEmail.setText(model1.getValueAt(i,6).toString());
        tfMatKhau.setText(model1.getValueAt(i,7).toString());
        Main.connection.cnSQL("jdbc:sqlserver://DESKTOP-JJSJBVA\\SQLEXPRESS:1433;databaseName=QLDV;", "nhom13","9876543210");
        String tvSQL11 = "select * from [GDlist] where MaKH = "+MaKHsl;
        ResultSet rsgd1 = Main.connection.HienThongTin(tvSQL11);
        Object[] obj = new Object[]{"Mã giao dịch","Mã chuyến bay","Điểm đi","Điểm đến","Tổng vé","Vé khứ hồi","Hạng ghế","Hành lý","Tổng chi phí"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        tblKhachHang1.setModel(tableModel);
        int c = 0;
        try {
            while (rsgd1.next()) {
                Object[] item = new Object[9];
                item[0] = rsgd1.getInt("MaHD");
                item[1] = rsgd1.getInt("MaCB");
                item[2] = rsgd1.getString("DiemDi");
                item[3] = rsgd1.getString("DiemDen");
                item[4] = rsgd1.getString("TongVe");
                item[5] = rsgd1.getString("VeKhuHoi");
                item[6] = rsgd1.getString("HangGhe");
                item[7] = rsgd1.getString("HanhLy");
                item[8] = rsgd1.getString("TongCP");
                tableModel.addRow(item);
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_tblKhachHangMouseClicked

    private void tblChuyenBayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChuyenBayMouseClicked
        // TODO add your handling code here:
        int i = tblChuyenBay.getSelectedRow();
        TableModel model1=tblChuyenBay.getModel();
        tfMaCB.setText(model1.getValueAt(i,1).toString());
        String MaCBsl = model1.getValueAt(i,1).toString();
        tfDDi.setText(model1.getValueAt(i,2).toString());
        tfDDen.setText(model1.getValueAt(i,3).toString());
        tfTgDi.setText(model1.getValueAt(i,4).toString());
        tfTgDen.setText(model1.getValueAt(i,5).toString());
        tfKC.setText(model1.getValueAt(i,6).toString());
        tfCP.setText(model1.getValueAt(i,7).toString());
        Main.connection.cnSQL("jdbc:sqlserver://DESKTOP-JJSJBVA\\SQLEXPRESS:1433;databaseName=QLDV;", "nhom13","9876543210");
        String tvSQL11 = "select * from [GDlist] where MaCB = "+MaCBsl;
        ResultSet rsgd1 = Main.connection.HienThongTin(tvSQL11);
        Object[] obj = new Object[]{"Mã giao dịch","Mã khách hàng","HoTen","Tổng vé","Vé khứ hồi","Hạng ghế","Hành lý","Tổng chi phí"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        tblChuyenBay1.setModel(tableModel);
        int c = 0;
        try {
            while (rsgd1.next()) {
                Object[] item = new Object[9];
                item[0] = rsgd1.getInt("MaHD");
                item[1] = rsgd1.getInt("MaKH");
                item[2] = rsgd1.getString("HoTen");
                item[3] = rsgd1.getString("TongVe");
                item[4] = rsgd1.getString("VeKhuHoi");
                item[5] = rsgd1.getString("HangGhe");
                item[6] = rsgd1.getString("HanhLy");
                item[7] = rsgd1.getString("TongCP");
                tableModel.addRow(item);
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_tblChuyenBayMouseClicked

    private void btnDelKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelKHActionPerformed
        // TODO add your handling code here:
        int i = tblKhachHang.getSelectedRow();
        String delMaKH = tblKhachHang.getValueAt(i,1).toString();
        String tvSQL = "delete from KhachHang where MaKH = " +delMaKH;
        Main.connection.cnSQL("jdbc:sqlserver://DESKTOP-JJSJBVA\\SQLEXPRESS:1433;databaseName=QLDV;", "nhom13","9876543210");
        System.out.println(tvSQL);
        try{
            Main.connection.ChinhSuaThongTin(tvSQL);
            JOptionPane.showMessageDialog(null,"Xóa thành công");
        }
        catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Xóa thất bại");
                }
    }//GEN-LAST:event_btnDelKHActionPerformed

    private void btnFindidKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindidKHActionPerformed
        // TODO add your handling code here:
        if(tfFindidKH.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Bạn chưa nhập thông tin");
        }
        else{
            Main.connection.cnSQL("jdbc:sqlserver://DESKTOP-JJSJBVA\\SQLEXPRESS:1433;databaseName=QLDV;", "nhom13","9876543210");
            String tvSQL2 = "select * from KhachHang where MaKH = '"+tfFindidKH.getText()+"'";
            ResultSet rsFkh = Main.connection.HienThongTin(tvSQL2);
            Object[] obj = new Object[]{"STT", "Mã khách hàng", "Họ và tên","Giới tính","Ngày sinh","Số điện thoại","Email","Mật khẩu"};
            DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
            tblKhachHang.setModel(tableModel);
            int c = 0;
            try {
                while (rsFkh.next()) {
                    c++;
                    Object[] item = new Object[8];
                    item[0] = c;
                    item[1] = rsFkh.getInt("MaKH");
                    item[2] = rsFkh.getString("HoTen");
                    item[3] = rsFkh.getString("GioiTinh");
                    item[4] = rsFkh.getString("NgaySinh");
                    item[5] = rsFkh.getString("SDT");
                    item[6] = rsFkh.getString("Email");
                    item[7] = rsFkh.getString("MatKhau");
                    tableModel.addRow(item);
                }
            } catch (SQLException ex) {
                System.out.println(ex.toString());
            }
        }
    }//GEN-LAST:event_btnFindidKHActionPerformed

    private void btnFindidCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindidCBActionPerformed
        // TODO add your handling code here:
        if(tfFindidCB.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Bạn chưa nhập thông tin");
        }
        else{
            Main.connection.cnSQL("jdbc:sqlserver://DESKTOP-JJSJBVA\\SQLEXPRESS:1433;databaseName=QLDV;", "nhom13","9876543210");
            String tvSQL2 = "select * from ChuyenBay where MaCB = '"+tfFindidCB.getText()+"'";
            ResultSet rsFcb = Main.connection.HienThongTin(tvSQL2);
            Object[] obj = new Object[]{"STT", "Mã chuyến bay", "Địa điểm đi","Địa điểm đến","Thời gian đi","Thời gian đến","Khoảng cách","Chi phí"};
            DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
            tblChuyenBay.setModel(tableModel);
            int c = 0;
            try {
                while (rsFcb.next()) {
                    c++;
                    Object[] item = new Object[8];
                    item[0] = c;
                    item[1] = rsFcb.getInt("MaCB");
                    item[2] = rsFcb.getString("DiemDi");
                    item[3] = rsFcb.getString("DiemDen");
                    item[4] = rsFcb.getString("TgDi");
                    item[5] = rsFcb.getString("TgDen");
                    item[6] = rsFcb.getString("KhoangCach");
                    item[7] = rsFcb.getString("ChiPhi");
                    tableModel.addRow(item);
                }
            } 
            catch (SQLException ex) {
                System.out.println(ex.toString());
            }
        }
    }//GEN-LAST:event_btnFindidCBActionPerformed

    private void tblThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThongKeMouseClicked
        // TODO add your handling code here:
        int i = tblThongKe.getSelectedRow();
        TableModel modeltk=tblThongKe.getModel();
        String MaHDSL = modeltk.getValueAt(i,0).toString();
        lbMaKH.setText(modeltk.getValueAt(i,1).toString());
        lbHoTen.setText(modeltk.getValueAt(i,2).toString());
        lbMaCB.setText(modeltk.getValueAt(i,3).toString());
        lbDDi.setText(modeltk.getValueAt(i,4).toString());
        lbDDen.setText(modeltk.getValueAt(i,5).toString());
        lbVeNgL.setText(modeltk.getValueAt(i,6).toString()+" Vé");
        lbVeTrE.setText(modeltk.getValueAt(i,7).toString()+" Vé");
        lbVeSoS.setText(modeltk.getValueAt(i,8).toString()+" Vé");
        lbTCP.setText(modeltk.getValueAt(i,9).toString()+" VND");
        Main.connection.cnSQL("jdbc:sqlserver://DESKTOP-JJSJBVA\\SQLEXPRESS:1433;databaseName=QLDV;", "nhom13","9876543210");
        String tvSQL2 = "select * from [GDlist] where MaHD = "+MaHDSL;
        ResultSet rsFhd = Main.connection.HienThongTin(tvSQL2);
        try {
            while (rsFhd.next()){
                lbVeNgL.setText(rsFhd.getString("VeNguoiLon"));
                lbVeTrE.setText(rsFhd.getString("VeTreEm"));
                lbVeSoS.setText(rsFhd.getString("VeSoSinh"));
                lbVKH.setText(rsFhd.getString("VeKhuHoi"));
                lbHG.setText(rsFhd.getString("HangGhe"));
                lbHL.setText(rsFhd.getString("HanhLy"));
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_tblThongKeMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DangNhap dn = new DangNhap();
        dn.show();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfCMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCMTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCMTActionPerformed

    private void tblKhachHang1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHang1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblKhachHang1MouseClicked

    private void tblChuyenBay1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChuyenBay1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblChuyenBay1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }
    public void KHlist(){
        Main.connection.cnSQL("jdbc:sqlserver://DESKTOP-JJSJBVA\\SQLEXPRESS:1433;databaseName=QLDV;", "nhom13","9876543210");
        String tvSQL1 = "select * from KhachHang";
        ResultSet rskh = Main.connection.HienThongTin(tvSQL1);
        Object[] obj = new Object[]{"STT", "Mã khách hàng", "Họ và tên","Giới tính","Ngày sinh","Số điện thoại","Email","Mật khẩu"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        tblKhachHang.setModel(tableModel);
        int c = 0;
        try {
            while (rskh.next()) {
                c++;
                Object[] item = new Object[8];
                item[0] = c;
                item[1] = rskh.getInt("MaKH");
                item[2] = rskh.getString("HoTen");
                item[3] = rskh.getString("GioiTinh");
                item[4] = rskh.getString("NgaySinh");
                item[5] = rskh.getString("SDT");
                item[6] = rskh.getString("Email");
                item[7] = rskh.getString("MatKhau");
                tableModel.addRow(item);
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }
    public void CBlist(){
        Main.connection.cnSQL("jdbc:sqlserver://DESKTOP-JJSJBVA\\SQLEXPRESS:1433;databaseName=QLDV;", "nhom13","9876543210");
        String tvSQL2 = "select * from [CBlist]";
        ResultSet rsdv = Main.connection.HienThongTin(tvSQL2);
        Object[] obj = new Object[]{"STT","Mã Chuyến bay","Điểm đi","Điểm đến","Thời gian đi","Thời gian đến","Khoảng cách","Chi phí","Số ghế"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        tblChuyenBay.setModel(tableModel);
        int c = 0;
        try {
            while (rsdv.next()) {
                c++;
                Object[] item = new Object[9];
                item[0] = c;
                item[1] = rsdv.getInt("MaCB");
                item[2] = rsdv.getString("DiemDi");
                item[3] = rsdv.getString("DiemDen");
                item[4] = rsdv.getString("TgDi");
                item[5] = rsdv.getString("TgDen");
                item[6] = rsdv.getString("KhoangCach");
                item[7] = rsdv.getString("ChiPhi");
                item[8] = rsdv.getString("Ghe");
                tableModel.addRow(item);
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }
    public boolean KiemTraRongCB() {
        if (tfDDi.getText().equals("") || tfDDen.getText().equals("") || tfTgDi.getText().equals("") || tfTgDen.getText().equals("") || tfKC.getText().equals("")
                || tfCP.getText().equals("") ) {
            return true;
        }
        return false;
    }
    public boolean KiemTraRongKH() {
        if (tfHoTen.getText().equals("") || tfNgaySinh.getText().equals("") || tfEmail.getText().equals("") || tfSDT.getText().equals("") || tfMatKhau.getText().equals("")
                || (!Nam.isSelected() && !Nu.isSelected())) {
            return true;
        }
        return false;
    }
    public void GDlist(){
        Main.connection.cnSQL("jdbc:sqlserver://DESKTOP-JJSJBVA\\SQLEXPRESS:1433;databaseName=QLDV;", "nhom13","9876543210");
        String tvSQL11 = "select * from [GDlist]";
        ResultSet rsgd = Main.connection.HienThongTin(tvSQL11);
        Object[] obj = new Object[]{"Mã giao dịch","Mã khách hàng","Họ tên","Mã chuyến bay","Điểm đi","Điểm đến","Vé người lớn","Vé trẻ em","Vé sơ sinh","Tổng chi phí"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        tblThongKe.setModel(tableModel);
        try {
            while (rsgd.next()) {
                Object[] item = new Object[10];
                item[0] = rsgd.getInt("MaHD");;
                item[1] = rsgd.getInt("MaKH");
                item[2] = rsgd.getString("HoTen");
                item[3] = rsgd.getInt("MaCB");
                item[4] = rsgd.getString("DiemDi");
                item[5] = rsgd.getString("DiemDen");
                item[6] = rsgd.getString("VeNguoiLon");
                item[7] = rsgd.getString("VeTreEm");
                item[8] = rsgd.getString("VeSoSinh");
                item[9] = rsgd.getString("TongCP");
                tableModel.addRow(item);
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Nam;
    private javax.swing.JRadioButton Nu;
    private javax.swing.JButton btnAddCB;
    private javax.swing.JButton btnAddKH;
    private javax.swing.JButton btnDelCB;
    private javax.swing.JButton btnDelKH;
    private javax.swing.JButton btnFindidCB;
    private javax.swing.JButton btnFindidKH;
    private javax.swing.JButton btnFixCB;
    private javax.swing.JButton btnFixKH;
    private javax.swing.JButton btnShowCB;
    private javax.swing.JButton btnShowKH;
    private javax.swing.JButton btnShowTK;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lbDDen;
    private javax.swing.JLabel lbDDi;
    private javax.swing.JLabel lbHG;
    private javax.swing.JLabel lbHL;
    private javax.swing.JLabel lbHoTen;
    private javax.swing.JLabel lbMaCB;
    private javax.swing.JLabel lbMaKH;
    private javax.swing.JLabel lbTCP;
    private javax.swing.JLabel lbVKH;
    private javax.swing.JLabel lbVeNgL;
    private javax.swing.JLabel lbVeSoS;
    private javax.swing.JLabel lbVeTrE;
    private javax.swing.JTable tblChuyenBay;
    private javax.swing.JTable tblChuyenBay1;
    private javax.swing.JTable tblKhachHang;
    private javax.swing.JTable tblKhachHang1;
    private javax.swing.JTable tblThongKe;
    private javax.swing.JTextField tfCMT;
    private javax.swing.JTextField tfCP;
    private javax.swing.JTextField tfDDen;
    private javax.swing.JTextField tfDDi;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfFindidCB;
    private javax.swing.JTextField tfFindidKH;
    private javax.swing.JTextField tfHoTen;
    private javax.swing.JTextField tfKC;
    private javax.swing.JTextField tfMaCB;
    private javax.swing.JTextField tfMaKH;
    private javax.swing.JTextField tfMatKhau;
    private javax.swing.JTextField tfNgaySinh;
    private javax.swing.JTextField tfSDT;
    private javax.swing.JTextField tfSG;
    private javax.swing.JTextField tfTgDen;
    private javax.swing.JTextField tfTgDi;
    // End of variables declaration//GEN-END:variables
}
